[package]
name = "beetle-collatz"
version = "0.3.4"
edition = "2021"
authors = ["beetle"]
description = "A collection of functions relating to the Collatz conjecture"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = {version = "1.6.1", optional = true}

[features]
default = []
threaded = ["dep:rayon"]

