[package]
name = "beetle-collatz"
version = "0.4.0"
edition = "2021"
authors = ["beetle"]
description = "A collection of functions relating to the Collatz conjecture"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
no-panic = "0.1.20"
num = "0.4.0"
# rayon = {version = "1.6.1", optional = true}
# rayon = "1.6.1"

[features]
default = []
# threaded = ["dep:rayon"]

