[package]
name = "beetle-collatz"
version = "0.5.7"
edition = "2021"
authors = ["beetle"]
description = "A collection of functions relating to the Collatz conjecture"
license = "MIT"
repository = "https://github.com/Mearkatz/beetle_collatz"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
beetle-nonzero = "0.2.9"
num = "0.4.0"

[features]
default = []

